language: python

branches:
  except:
    - gh-pages

stages:
  - test
  - name: deploy
    if: tag IS present

jobs:
  include:
    - python: 3.6
      env: TOXENV=check,unit_py3_6
    - python: 3.8
      sudo: true
      env: TOXENV=check,unit_py3_8

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y git

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox "-n $(nproc)"
