from io import StringIO

from pytest import raises
from unittest.mock import patch, Mock, call

from kiwi_keg.tools import lib_image

config_kiwi = '''<?xml version="1.0" encoding="utf-8"?>
<!-- Image description generated by keg on 2025-11-11 17:04:47 -->
<image schemaversion="7.5" name="image_name" displayname="image_display_name">
    <preferences>
        <version>1.2.3</version>
    </preferences>
</image>
'''

config_kiwi_no_ver = '''<?xml version="1.0" encoding="utf-8"?>
<!-- Image description generated by keg on 2025-11-11 17:04:47 -->
<image schemaversion="7.5" name="image_name" displayname="image_display_name">
    <preferences/>
</image>
'''


def test_lib_image_get_image_version():
    assert lib_image.get_image_version(StringIO(config_kiwi)) == '1.2.3'


def test_lib_image_get_image_version_no_ver():
    with raises(RuntimeError) as e_info:
        lib_image.get_image_version(StringIO(config_kiwi_no_ver))
    assert str(e_info.value) == 'Cannot determine image version.'


def test_lib_image_get_bumped_image_version():
    assert lib_image.get_bumped_image_version(StringIO(config_kiwi)) == '1.2.4'


@patch('kiwi_keg.tools.lib_image.SourceInfoGenerator')
@patch('kiwi_keg.tools.lib_image.KegGenerator')
@patch('kiwi_keg.tools.lib_image.KegImageDefinition')
def test_lib_image_generate_image_description(mock_image_definition, mock_generator, mock_source_info_gen):
    mock_repo = Mock()
    mock_repo.pathname = 'repo_pathname'
    lib_image.generate_image_description('image_source', {'repo': mock_repo}, True, 'image_version', True, 'outdir', ['arch'])
    mock_image_definition.assert_called_with(
        image_name='image_source',
        recipes_roots=['repo_pathname'],
        track_sources=True,
        image_version='image_version'
    )
    mock_generator.assert_has_calls([
        call(image_definition=mock_image_definition(), dest_dir='outdir', archs=['arch']),
        call().create_kiwi_description(overwrite=True),
        call().create_custom_scripts(overwrite=True),
        call().create_overlays(disable_root_tar=False, overwrite=True),
        call().create_custom_files(overwrite=True),
        call().create_multibuild_file(overwrite=True)
    ])
    mock_source_info_gen.assert_has_calls([
        call(mock_image_definition(), dest_dir='outdir'),
        call().write_source_info()
    ])
